### PR TITLE
Connection: support leader redirection (issue #3)

### LINKED ISSUE #3: Client should route request to leader on receipt of 301
The 3.0 release series of rqlite now returns 301 and the location of the leader set in a header within the response, if the node receiving the request is not the leader. For example:

```
$ curl -G -v 'localhost:4004/db/query?pretty&timings' --data-urlencode 'q=SELECT * FROM foo'
*   Trying ::1...
* connect to ::1 port 4004 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 4004 (#0)
> GET /db/query?pretty&timings&q=SELECT%20%2A%20FROM%20foo HTTP/1.1
> Host: localhost:4004
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Location: http://localhost:4001/db/query
< Date: Mon, 02 May 2016 19:40:20 GMT
< Content-Length: 65
< Content-Type: text/html; charset=utf-8
< 
<a href="http://localhost:4001/db/query">Moved Permanently</a>.

* Connection #0 to host localhost left intact
```

The Python client could detect when this happens, and automatically re-issue the request to the leader.

### PR DESCRIPTION
**Pull request by zmedico**
@otoolep This fixes https://github.com/rqlite/pyrqlite/issues/3.

### CODE REVIEW

**Comment by otoolep** [comment]
Nice. 🚢

**Comment by otoolep** [comment]
Only suggestion is to support a flag to the `Connection` type allowing the client to disable following the redirect. Perhaps someone wouldn't want it. You need to pass `-L` to curl for it to happen automatically, for example.

**Comment by zmedico** [comment]
Added a `max_redirects` parameter which disables redirection when set to 0. Default is currently unlimited.

**Comment by otoolep** [comment]
Even better -- LGTM.

**Pull request merged**
