### PR TITLE
Connection: add :memory: support

### PR DESCRIPTION
**Pull request by zmedico**
@alanjds

### CODE REVIEW

**Comment by alanjds** [comment]
I dont really like this. What about:

1. Implement `:memory:` as `localhost`?
or
1. Change the tests?

**Comment by zmedico** [comment]
> 1. Implement :memory: as localhost?

Sure, that would be fine, but requires some work. I'm really not happy with the current state, where we've got tests that we expect to fail. I like to have all tests either passing or marked somehow. Otherwise there's too much "noise", making it difficult to separate regressions from expected failures. I'd really just like to reduce the "noise" level ASAP.

> 2. Change the tests?

Sure, if it's easy. How do you feel about deleting them? As said, reducing the noise level is my highest priority.

**Comment by alanjds** [comment]
Please take a look at https://github.com/zmedico/pyrqlite/pull/1. Is this acceptable?

**Comment by alanjds** [comment]
This is nicer than before. Will you remove the `@unittest.skip` calls?

**Comment by zmedico** [comment]
Yeah, we're no going to the `@unittest.skip` calls when I'm finished. I'm working in this branch:

https://github.com/zmedico/pyrqlite/commits/ephemeral

**Pull request merged**
