### PR TITLE
Connection: only use host and port from Location header

### LINKED ISSUE #19: There are differences between access rqlite master and slave with pyrqlite
I use sqlalchemy and pyrqlite accessing rqlite db. Here is my sqlalchemy engine
`engine = create_engine('rqlite+pyrqlite://' +ip +':4001/', poolclass=NullPool)`
It can work properly when there are only one rqlite node. After there are three rqlite nodes,I found that only ip is rqlite master ip, it can work properly.When ip is rqlite slave nodes, I got a error as bellow from sqlalchemy:
`No JSON object could be decoded`
My rqlited starts as:
```
rqlited -http-addr 0.0.0.0:4001 -http-adv-addr 192.168.2.14:4001 -raft-addr 0.0.0.0:4002 -raft-adv-addr 192.168.2.14:4002 ~/node.1
rqlited -http-addr 0.0.0.0:4001 -http-adv-addr 192.168.2.13:4001 -raft-addr 0.0.0.0:4002 -raft-adv-addr 192.168.2.13:4002 -join http://192.168.2.14:4001 ~/node.2
rqlited -http-addr 0.0.0.0:4001 -http-adv-addr 192.168.2.15:4001 -raft-addr 0.0.0.0:4002 -raft-adv-addr 192.168.2.15:4002 -join http://192.168.2.14:4001 ~/node.3
```
I don't think this is rqlite server problem, because when I use rqlite client with --host parameter, it can work properly.So is this a pyrqlite issue?

### PR DESCRIPTION
**Pull request by zmedico**
Suggested-by: @lkxjtu
Closes: https://github.com/rqlite/pyrqlite/issues/19

### CODE REVIEW

**Comment by otoolep** [comment]
LGTM.
```
>>> new_uri="https://localhost:4001/db/query"
>>> urlparse(new_uri)
ParseResult(scheme='https', netloc='localhost:4001', path='/db/query', params='', query='', fragment='')
>>> location=urlparse(new_uri)
>>> location.hostname
'localhost'
>>> location.port
4001
```
Perhaps the rqlite software should have returned the full URL, including the query param?

**Comment by otoolep** [comment]
If I change rqlite to return the full URL, and release rqlite v4.0.2, this change would be unrequired. I could also update all client libraries relying on current behaviour.

It's not great, as it would be somewhat of a breaking change, but it looks rqlite has been setting a bad `Location` header all this time. Thoughts?

**Comment by zmedico** [comment]
You could update the client libraries for forward compatibility, and wait some time before changing the rqlited behavior.

**Comment by otoolep** [comment]
FWIW, this change should fix it: https://github.com/rqlite/rqlite/pull/337

**Comment by zmedico** [comment]
I have a [branch](https://github.com/zmedico/pyrqlite/tree/ephemeral) where I've been working on unit test support for spawning rqlited. I might add a test for this, where it purposefully connects to a non-master rqlited instance.

**Comment by zmedico** [comment]
Closing since https://github.com/rqlite/rqlite/pull/337 made this unnecessary.

**Pull request closed without merging**
